WITH RECURSIVE EMPTY_HOUR_TABLE AS (
    SELECT 0 AS HOUR, 0 AS COUNT
    UNION
    SELECT HOUR + 1 as HOUR, COUNT
    FROM EMPTY_HOUR_TABLE
    WHERE HOUR < 23
)

select EHT.HOUR, (EHT.COUNT + COUNT(AO.ANIMAL_ID)) AS COUNT
from EMPTY_HOUR_TABLE EHT LEFT JOIN ANIMAL_OUTS AO
ON EHT.HOUR = HOUR(AO.DATETIME)
GROUP BY EHT.HOUR
ORDER BY HOUR;